-- ###########################################
-- # Create
-- ###########################################

-- Create normal entities
    
CREATE TABLE TB_ROLES (
  ID BIGINT NOT NULL,
  CODE VARCHAR(255) NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(4000),
  UPDATE_DATE_TZ VARCHAR(50),
  UPDATE_DATE DATETIME,
  UUID VARCHAR(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR(50),
  CREATED_DATE DATETIME,
  CREATED_BY VARCHAR(50),
  LAST_UPDATED_TZ VARCHAR(50),
  LAST_UPDATED DATETIME,
  LAST_UPDATED_BY VARCHAR(50),
  VERSION BIGINT NOT NULL
);


CREATE TABLE TB_APPS (
  ID BIGINT NOT NULL,
  CODE VARCHAR(255) NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(4000),
  UPDATE_DATE_TZ VARCHAR(50),
  UPDATE_DATE DATETIME,
  UUID VARCHAR(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR(50),
  CREATED_DATE DATETIME,
  CREATED_BY VARCHAR(50),
  LAST_UPDATED_TZ VARCHAR(50),
  LAST_UPDATED DATETIME,
  LAST_UPDATED_BY VARCHAR(50),
  VERSION BIGINT NOT NULL
);


CREATE TABLE TB_USERS (
  ID BIGINT NOT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  SURNAME VARCHAR(255) NOT NULL,
  MAIL VARCHAR(255) NOT NULL,
  UPDATE_DATE_TZ VARCHAR(50),
  UPDATE_DATE DATETIME,
  UUID VARCHAR(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR(50),
  CREATED_DATE DATETIME,
  CREATED_BY VARCHAR(50),
  LAST_UPDATED_TZ VARCHAR(50),
  LAST_UPDATED DATETIME,
  LAST_UPDATED_BY VARCHAR(50),
  VERSION BIGINT NOT NULL
);


CREATE TABLE TB_INTERNATIONAL_STRINGS (
  ID BIGINT NOT NULL,
  VERSION BIGINT NOT NULL
);


CREATE TABLE TB_EXTERNAL_ITEMS (
  ID BIGINT NOT NULL,
  CODE VARCHAR(255) NOT NULL,
  URI VARCHAR(4000) NOT NULL,
  URN VARCHAR(4000) NOT NULL,
  MANAGEMENT_APP_URL VARCHAR(4000),
  VERSION BIGINT NOT NULL,
  TITLE_FK BIGINT,
  TYPE VARCHAR(255) NOT NULL
);


CREATE TABLE TB_ACCESS (
  ID BIGINT NOT NULL,
  REMOVAL_DATE_TZ VARCHAR(50),
  REMOVAL_DATE DATETIME,
  UPDATE_DATE_TZ VARCHAR(50),
  UPDATE_DATE DATETIME,
  UUID VARCHAR(36) NOT NULL,
  CREATED_DATE_TZ VARCHAR(50),
  CREATED_DATE DATETIME,
  CREATED_BY VARCHAR(50),
  LAST_UPDATED_TZ VARCHAR(50),
  LAST_UPDATED DATETIME,
  LAST_UPDATED_BY VARCHAR(50),
  VERSION BIGINT NOT NULL,
  ROLE_FK BIGINT NOT NULL,
  APP_FK BIGINT NOT NULL,
  USER_FK BIGINT NOT NULL,
  OPERATION_FK BIGINT
);


CREATE TABLE TB_LOCALISED_STRINGS (
  ID BIGINT NOT NULL,
  LABEL VARCHAR(4000) NOT NULL,
  LOCALE VARCHAR(255) NOT NULL,
  VERSION BIGINT NOT NULL,
  INTERNATIONAL_STRING_FK BIGINT NOT NULL
);



-- Create many to many relations
    

-- Primary keys
    
ALTER TABLE TB_ROLES ADD CONSTRAINT PK_TB_ROLES
	PRIMARY KEY (ID)
;

ALTER TABLE TB_APPS ADD CONSTRAINT PK_TB_APPS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_USERS ADD CONSTRAINT PK_TB_USERS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_INTERNATIONAL_STRINGS ADD CONSTRAINT PK_TB_INTERNATIONAL_STRINGS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_EXTERNAL_ITEMS ADD CONSTRAINT PK_TB_EXTERNAL_ITEMS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_ACCESS ADD CONSTRAINT PK_TB_ACCESS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT PK_TB_LOCALISED_STRINGS
	PRIMARY KEY (ID)
;

    

-- Unique constraints

ALTER TABLE TB_ROLES
    ADD CONSTRAINT UQ_TB_ROLES UNIQUE (UUID)
;


ALTER TABLE TB_APPS
    ADD CONSTRAINT UQ_TB_APPS UNIQUE (UUID)
;


ALTER TABLE TB_USERS
    ADD CONSTRAINT UQ_TB_USERS UNIQUE (UUID)
;


ALTER TABLE TB_INTERNATIONAL_STRINGS
	ADD CONSTRAINT UQ_TB_INTERNATIONAL_STRINGS UNIQUE (ID)
;


ALTER TABLE TB_EXTERNAL_ITEMS
	ADD CONSTRAINT UQ_TB_EXTERNAL_ITEMS UNIQUE (ID)
;


ALTER TABLE TB_ACCESS
    ADD CONSTRAINT UQ_TB_ACCESS UNIQUE (UUID)
;


ALTER TABLE TB_LOCALISED_STRINGS
	ADD CONSTRAINT UQ_TB_LOCALISED_STRINGS UNIQUE (ID)
;



-- Foreign key constraints
    

  
  
  
  
  
  
  
  
ALTER TABLE TB_EXTERNAL_ITEMS ADD CONSTRAINT FK_TB_EXTERNAL_ITEMS_TITLE_FK
	FOREIGN KEY (TITLE_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE TB_ACCESS ADD CONSTRAINT FK_TB_ACCESS_ROLE_FK
	FOREIGN KEY (ROLE_FK) REFERENCES TB_ROLES (ID)
;
ALTER TABLE TB_ACCESS ADD CONSTRAINT FK_TB_ACCESS_APP_FK
	FOREIGN KEY (APP_FK) REFERENCES TB_APPS (ID)
;
ALTER TABLE TB_ACCESS ADD CONSTRAINT FK_TB_ACCESS_USER_FK
	FOREIGN KEY (USER_FK) REFERENCES TB_USERS (ID)
;
ALTER TABLE TB_ACCESS ADD CONSTRAINT FK_TB_ACCESS_OPERATION_FK
	FOREIGN KEY (OPERATION_FK) REFERENCES TB_EXTERNAL_ITEMS (ID)
;

  
ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT FK_TB_LOCALISED_STRINGS_INTERNATIONAL_STRING_FK
	FOREIGN KEY (INTERNATIONAL_STRING_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

  

    


