-- ----------------------------------------------------------------------------------------------------
-- METAMAC-2215 - [BBDD] Las constraints no pueden ser DEFERRED porque no hay soporte para SQLServer
-- ----------------------------------------------------------------------------------------------------

ALTER TABLE TB_ROLES DROP CONSTRAINT ROLES_CODE;
ALTER TABLE TB_USERS DROP CONSTRAINT USERS_USERNAME;
ALTER TABLE TB_APPS DROP CONSTRAINT APPS_CODE;
ALTER TABLE TB_ACCESS DROP CONSTRAINT ACCESS_UNIQUE;
ALTER TABLE TB_LOCALISED_STRINGS DROP CONSTRAINT LOCALE_INTERNATIONAL;


ALTER TABLE TB_ROLES ADD CONSTRAINT ROLES_CODE UNIQUE(CODE);
ALTER TABLE TB_USERS ADD CONSTRAINT USERS_USERNAME UNIQUE(USERNAME);
ALTER TABLE TB_APPS ADD CONSTRAINT APPS_CODE UNIQUE(CODE);
ALTER TABLE TB_ACCESS ADD CONSTRAINT ACCESS_UNIQUE UNIQUE(ROLE_FK, APP_FK, USER_FK, OPERATION_FK, REMOVAL_DATE);
ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT LOCALE_INTERNATIONAL UNIQUE(LOCALE, INTERNATIONAL_STRING_FK);

commit;