-- ###########################################
-- # Drop
-- ###########################################


-- Disable Foreign key constraints
    

  
  
  
  
  
  
  
  
ALTER TABLE TB_EXTERNAL_ITEMS DROP CONSTRAINT FK_TB_EXTERNAL_ITEMS_TITLE_FK;

  
ALTER TABLE TB_ACCESS DROP CONSTRAINT FK_TB_ACCESS_ROLE_FK;
ALTER TABLE TB_ACCESS DROP CONSTRAINT FK_TB_ACCESS_APP_FK;
ALTER TABLE TB_ACCESS DROP CONSTRAINT FK_TB_ACCESS_USER_FK;
ALTER TABLE TB_ACCESS DROP CONSTRAINT FK_TB_ACCESS_OPERATION_FK;

  
ALTER TABLE TB_LOCALISED_STRINGS DROP CONSTRAINT FK_TB_LOCALISED_STRINGS_INTERNATIONAL_STRING_FK;

  

    
    
-- Drop many to many relations
    
-- Drop normal entities
    
DROP TABLE TB_LOCALISED_STRINGS;

DROP TABLE TB_ACCESS;

DROP TABLE TB_EXTERNAL_ITEMS;

DROP TABLE TB_INTERNATIONAL_STRINGS;

DROP TABLE TB_USERS;

DROP TABLE TB_APPS;

DROP TABLE TB_ROLES;
